name: ramp-meg
channels:
  - conda-forge
  - defaults
dependencies:
  - python >=3.7
  - numpy
  - scikit-learn >=0.22
  - scipy
  - pandas
  - matplotlib
  - tensorflow-gpu
  - pytorch
  - keras
  - lightgbm
  - pip
  - pip:
    - osfclient
    - ramp-workflow
    - ramp-utils
    - pot
    - imbalanced-learn
    - gudhi
    - xgboost
    - catboost
